apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-cv
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: cv-app-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:quantum-engine-377722.svc.id.goog[cv/cv-ksa]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-boutique
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: boutique-app-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:quantum-engine-377722.svc.id.goog[boutique/boutique-ksa]
